import { calculateArea } from "../utils.js";

// 1. 各機型 Damper 佈局圖
export const damperLayoutsByModel = {
  vt8: "./img/damper-layout-vt8.jpg",
  vt7: "./img/damper-layout-vt7.jpg",
  vt6: "./img/damper-layout-vt6.jpg",
  vt5: "./img/damper-layout-vt5.jpg",
  vt1: "./img/damper-layout-vt1.jpg",
};

// 2. 風量量測設定 (所有機型)
export const allDryerAirVolumeMeasurements = {
  vt8: [
    {
      id: "chamber1_supply",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-supply.jpg",
      order: 100,
      floor: "3F",
      probeDepth: 35,
    },
    {
      id: "chamber2_supply_after_filter",
      label: "2室給氣(濾網後)",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-supply-after-filter.jpg",
      order: 101,
      floor: "3F",
      probeDepth: 35,
    },
    {
      id: "chamber2_supply_before_filter",
      label: "2室給氣(濾網前)",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-supply-before-filter.jpg",
      order: 102,
      floor: "3F",
      probeDepth: 35,
    },
    {
      id: "chamber1_exhaust_before_motor",
      label: "1室排氣(馬達前)",
      duct: "0.65*0.65",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-exhaust-before-motor.jpg",
      order: 103,
      floor: "5F",
      probeDepth: 43,
    },
    {
      id: "chamber2_exhaust_before_motor",
      label: "2室排氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-exhaust-before-motor.jpg",
      order: 104,
      floor: "5F",
      probeDepth: 33,
    },
    {
      id: "chamber1_upper_ac_supply",
      label: "1室上部AC給氣",
      duct: "Ф0.255",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply.jpg",
      order: 105,
      floor: "6F",
      probeDepth: 20,
    },
    {
      id: "chamber1_upper_ac_supply_front",
      label: "1室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply-front.jpg",
      order: 106,
      floor: "6F",
      probeDepth: 13,
    },
    {
      id: "chamber1_upper_ac_supply_rear",
      label: "1室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply-rear.jpg",
      order: 107,
      floor: "6F",
      probeDepth: 13,
    },
    {
      id: "chamber2_upper_ac_supply",
      label: "2室上部AC給氣",
      duct: "Ф0.255",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply.jpg",
      order: 108,
      floor: "6F",
      probeDepth: 25,
    },
    {
      id: "chamber2_upper_ac_supply_front",
      label: "2室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply-front.jpg",
      order: 109,
      floor: "6F",
      probeDepth: 13,
    },
    {
      id: "chamber2_upper_ac_supply_rear",
      label: "2室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply-rear.jpg",
      order: 110,
      floor: "6F",
      probeDepth: 13,
    },
    {
      id: "upper_ac_top_exhaust_outdoor",
      label: "上部AC+TOP排氣(屋外)",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt8-upper-ac-top-exhaust-outdoor.jpg",
      order: 111,
      floor: "5F",
      probeDepth: 18,
    },
    {
      id: "lower_ac_exhaust",
      label: "下部AC排氣",
      duct: "0.35*0.35",
      status: "normal",
      imageUrl: "./img/vt8-lower-ac-exhaust.jpg",
      order: 112,
      floor: "2F",
      probeDepth: 18,
    },
    {
      id: "lower_ac_exhaust_outdoor",
      label: "下部AC排氣(屋外)",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt8-lower-ac-exhaust-outdoor.jpg",
      order: 113,
      floor: "5F",
      probeDepth: 18,
    },
  ],
  vt7: [
    {
      id: "chamber1_supply_vt7",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-supply.jpg",
      order: 100,
      floor: "5F",
      probeDepth: 37,
    },
    {
      id: "chamber1_exhaust_vt7",
      label: "1室排氣",
      duct: "0.75*0.5",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-exhaust.jpg",
      order: 101,
      floor: "2F",
      probeDepth: 50,
    },
    {
      id: "chamber2_supply_vt7",
      label: "2室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-supply.jpg",
      order: 102,
      floor: "5F",
      probeDepth: 37,
    },
    {
      id: "chamber2_exhaust_vt7",
      label: "2室排氣",
      duct: "0.75*0.5",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-exhaust.jpg",
      order: 103,
      floor: "2F",
      probeDepth: 50,
    },
    {
      id: "chamber1_2_exhaust_vt7",
      label: "1、2室排氣",
      duct: "0.64*0.67",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-2-exhaust.jpg",
      order: 104,
      floor: "4F",
      probeDepth: 50,
    },
    {
      id: "chamber1_upper_ac_supply_upper_vt7",
      label: "１室上部AC給氣(上)",
      duct: "φ0.40",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-upper-ac-supply-upper.jpg",
      order: 105,
      floor: "7F",
      probeDepth: 25,
    },
    {
      id: "chamber1_upper_ac_supply_lower_vt7",
      label: "１室上部AC給氣(下)",
      duct: "φ0.40",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-upper-ac-supply-lower.jpg",
      order: 106,
      floor: "6F",
      probeDepth: 35,
    },
    {
      id: "chamber1_upper_ac_exhaust_vt7",
      label: "１室上部AC排氣",
      duct: "沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 107,
      floor: "沒量測點",
    },
    {
      id: "chamber2_upper_ac_supply_vt7",
      label: "２室上部AC給氣",
      duct: "φ0.255",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-upper-ac-supply.jpg",
      order: 108,
      floor: "6F",
      probeDepth: 25,
    },
    {
      id: "chamber2_upper_ac_exhaust_vt7",
      label: "２室上部AC排氣",
      duct: "沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 109,
      floor: "沒量測點",
    },
    {
      id: "top_exhaust_vt7",
      label: "TOP排氣",
      duct: "0.5*0.5",
      status: "normal",
      imageUrl: "./img/vt7-top-exhaust.jpg",
      order: 110,
      floor: "6F",
      probeDepth: 40,
    },
    {
      id: "upper_ac_exhaust_outdoor_vt7",
      label: "上部AC排氣(戶外)",
      duct: "φ0.35",
      status: "normal",
      imageUrl: "./img/vt7-upper-ac-exhaust-outdoor.jpg",
      order: 111,
      floor: "5F",
      probeDepth: 17,
    },
    {
      id: "lower_ac_supply_vt7",
      label: "下部AC給氣",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt7-lower-ac-supply.jpg",
      order: 112,
      floor: "2F",
      probeDepth: 25,
    },
    {
      id: "chamber2_lower_ac_exhaust_vt7",
      label: "2室下部AC排氣",
      duct: "0.5*0.37",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-lower-ac-exhaust.jpg",
      order: 113,
      floor: "3F",
      probeDepth: 35,
    },
  ],
  vt6: [
    {
      id: "chamber1_supply_vt6",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-supply.jpg",
      order: 100,
      floor: "5F",
      probeDepth: 35,
    },
    {
      id: "chamber1_exhaust_vt6",
      label: "1室排氣",
      duct: "0.85*0.58",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-exhaust.jpg",
      order: 101,
      floor: "2F",
      probeDepth: 47,
    },
    {
      id: "chamber2_supply_vt6",
      label: "2室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-supply.jpg",
      order: 102,
      floor: "5F",
      probeDepth: 35,
    },
    {
      id: "chamber2_exhaust_vt6",
      label: "2室排氣",
      duct: "0.85*0.28",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-exhaust.jpg",
      order: 103,
      floor: "2F",
      probeDepth: 47,
    },
    {
      id: "chamber1_upper_ac_supply_upper_vt6",
      label: "１室上部AC給氣(上)",
      duct: "φ0.4",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-supply-upper.jpg",
      order: 104,
      floor: "7F",
      probeDepth: 25,
    },
    {
      id: "chamber1_upper_ac_supply_lower_vt6",
      label: "１室上部AC給氣(下)",
      duct: "φ0.4",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-supply-lower.jpg",
      order: 105,
      floor: "6F",
      probeDepth: 25,
    },
    {
      id: "chamber1_upper_ac_exhaust_vt6",
      label: "１室上部AC排氣",
      duct: "0.6*0.35",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-exhaust.jpg",
      order: 106,
      floor: "7F",
      probeDepth: 40,
    },
    {
      id: "chamber2_upper_ac_supply_vt6",
      label: "２室上部AC給氣",
      duct: "φ0.25",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-upper-ac-supply.jpg",
      order: 107,
      floor: "6F",
      probeDepth: 20,
    },
    {
      id: "chamber2_upper_ac_exhaust_vt6",
      label: "２室上部AC排氣",
      duct: "0.6*0.35",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-upper-ac-exhaust.jpg",
      order: 108,
      floor: "6F",
      probeDepth: 40,
    },
    {
      id: "upper_ac_exhaust_1_2_vt6",
      label: "上部AC排氣(1、2室)",
      duct: "0.30*0.30",
      status: "normal",
      imageUrl: "./img/vt6-upper-ac-exhaust-1-2.jpg",
      order: 109,
      floor: "6F",
      probeDepth: 23,
    },
    {
      id: "top_exhaust_right_vt6",
      label: "TOP排氣-右",
      duct: "0.35*0.18",
      status: "normal",
      imageUrl: "./img/vt6-top-exhaust-right.jpg",
      order: 110,
      floor: "7F",
      probeDepth: 25,
    },
    {
      id: "top_exhaust_left_vt6",
      label: "TOP排氣-左",
      duct: "0.35*0.18",
      status: "normal",
      imageUrl: "./img/vt6-top-exhaust-left.jpg",
      order: 111,
      floor: "7F",
      probeDepth: 25,
    },
    {
      id: "lower_ac_supply_vt6",
      label: "下部AC給氣",
      duct: "測定危険",
      status: "dangerous",
      imageUrl: "",
      order: 112,
      floor: "測定危險",
    },
    {
      id: "lower_ac_exhaust_vt6",
      label: "下部AC排氣",
      duct: "0.3*0.42",
      status: "normal",
      imageUrl: "./img/vt6-lower-ac-exhaust.jpg",
      order: 113,
      floor: "2F",
      probeDepth: 30,
    },
  ],
  vt1: [
    {
      id: "chamber1_supply_motor_before_vt1",
      label: "１室給氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-supply-motor-before.jpg",
      order: 100,
      floor: "4F",
    },
    {
      id: "chamber1_supply_motor_after_vt1",
      label: "１室給氣(馬達後)",
      duct: "0.8*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-supply-motor-after.jpg",
      order: 101,
      floor: "4F",
    },
    {
      id: "chamber1_exhaust_motor_before_vt1",
      label: "１室排氣(馬達前)",
      duct: "0.55*0.63",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-exhaust-motor-before.jpg",
      order: 102,
      floor: "3F",
    },
    {
      id: "chamber1_exhaust_motor_after_vt1",
      label: "１室排氣(馬達後)",
      duct: "0.65*0.42",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-exhaust-motor-after.jpg",
      order: 103,
      floor: "3F",
    },
    {
      id: "chamber2_supply_motor_before_vt1",
      label: "２室給氣(馬達前)",
      duct: "0.35*0.35",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-supply-motor-before.jpg",
      order: 104,
      floor: "4F",
    },
    {
      id: "chamber2_supply_motor_after_vt1",
      label: "２室給氣(馬達後)",
      duct: "0.8*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-supply-motor-after.jpg",
      order: 105,
      floor: "4F",
    },
    {
      id: "chamber2_exhaust_motor_before_vt1",
      label: "２室排氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-exhaust-motor-before.jpg",
      order: 106,
      floor: "3F",
    },
    {
      id: "chamber2_exhaust_motor_after_vt1",
      label: "２室排氣(馬達後)",
      duct: "0.60*0.33",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-exhaust-motor-after.jpg",
      order: 107,
      floor: "3F",
    },
    {
      id: "chamber1_upper_ac_supply_vt1",
      label: "1室上部AC給氣",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-upper-ac-supply.jpg",
      order: 108,
      floor: "5F",
    },
    {
      id: "upper_ac_supply_vt1",
      label: "上部AC給氣",
      duct: "0.39*0.65",
      status: "normal",
      imageUrl: "./img/vt1-upper-ac-supply.jpg",
      order: 109,
      floor: "5F",
    },
    {
      id: "chamber2_upper_ac_supply_vt1",
      label: "2室上部AC給氣",
      duct: "0.3*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-upper-ac-supply.jpg",
      order: 110,
      floor: "5F",
    },
    {
      id: "top_roll_exhaust_fan_before_vt1",
      label: "TOP ROLL排氣室(風扇前)",
      duct: "0.5*0.22",
      status: "normal",
      imageUrl: "./img/vt1-top-roll-exhaust-fan-before.jpg",
      order: 111,
      floor: "5F",
    },
    {
      id: "top_roll_exhaust_fan_after_vt1",
      label: "TOP ROLL排氣室(風扇後)",
      duct: "0.7*0.45",
      status: "normal",
      imageUrl: "./img/vt1-top-roll-exhaust-fan-after.jpg",
      order: 112,
      floor: "5F",
    },
    {
      id: "lower_ac_supply_vt1",
      label: "下部AC給氣",
      duct: "0.39*0.39",
      status: "normal",
      imageUrl: "./img/vt1-lower-ac-supply.jpg",
      order: 113,
      floor: "2F",
    },
    {
      id: "lower_ac_exhaust_vt1",
      label: "下部AC排氣",
      duct: "0.38*0.34",
      status: "normal",
      imageUrl: "./img/vt1-lower-ac-exhaust.jpg",
      order: 114,
      floor: "2F",
    },
  ],
  vt5: [
    {
      id: "chamber1_supply_vt5",
      label: "１室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-supply.jpg",
      order: 100,
      floor: "5F",
    },
    {
      id: "chamber1_exhaust_vt5",
      label: "１室排氣",
      duct: "0.43*0.58",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-exhaust.jpg",
      order: 101,
      floor: "2F",
    },
    {
      id: "chamber2_supply_vt5",
      label: "２室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-supply.jpg",
      order: 102,
      floor: "5F",
    },
    {
      id: "chamber2_exhaust_vt5",
      label: "２室 排氣",
      duct: "0.35*0.37",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-exhaust.jpg",
      order: 103,
      floor: "2F",
    },
    {
      id: "chamber1_2_exhaust_vt5",
      label: "1、2室排氣",
      duct: "0.6*0.6",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-2-exhaust.jpg",
      order: 104,
      floor: "3F",
    },
    {
      id: "chamber1_upper_ac_supply_vt5",
      label: "１室上部AC給氣",
      duct: "φ0.24",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply.jpg",
      order: 105,
      floor: "6F",
    },
    {
      id: "chamber1_upper_ac_supply_front_vt5",
      label: "１室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply-front.jpg",
      order: 106,
      floor: "6F",
    },
    {
      id: "chamber1_upper_ac_supply_rear_vt5",
      label: "１室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply-rear.jpg",
      order: 107,
      floor: "6F",
    },
    {
      id: "chamber2_upper_ac_supply_vt5",
      label: "２室上部AC給氣",
      duct: "φ0.24",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply.jpg",
      order: 108,
      floor: "6F",
    },
    {
      id: "chamber2_upper_ac_supply_front_vt5",
      label: "２室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply-front.jpg",
      order: 109,
      floor: "6F",
    },
    {
      id: "chamber2_upper_ac_supply_rear_vt5",
      label: "２室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply-rear.jpg",
      order: 110,
      floor: "6F",
    },
    {
      id: "upper_ac_exhaust_vt5",
      label: "上部AC排氣",
      duct: "0.40*0.40 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 111,
      floor: "沒量測點",
    },
    {
      id: "lower_ac_supply_vt5",
      label: "下部AC給氣",
      duct: "0.39*0.39 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 112,
      floor: "沒量測點",
    },
    {
      id: "lower_ac_exhaust_vt5",
      label: "下部AC排氣",
      duct: "0.35*0.35 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 113,
      floor: "沒量測點",
    },
  ],
};

// 3. 輔助函式，根據機型取得風量測量設定並計算面積
export const getAirVolumeMeasurementsByModel = (model) => {
  const measurements = allDryerAirVolumeMeasurements[model] || [];
  const clonedMeasurements = JSON.parse(JSON.stringify(measurements));

  clonedMeasurements.forEach((m) => {
    if (m.status === "normal") {
      m.area = calculateArea(m.duct);
    } else {
      m.area = 0;
    }
    if (!m.imageUrl) {
      m.imageUrl = "";
    }
  });
  return clonedMeasurements;
};

// 4. 給排氣 DAMPER 設定 (所有機型)
// 輔助函式：建立一個包含通用屬性的 Damper 欄位設定陣列
const createDamperConfig = (fields) => {
  return fields.map((field) => ({
    ...field,
    recordTypes: ["conditionSetting"],
    group: "damperOpening",
    elemType: "number",
    inTable: true,
    csvHeader: `給排氣damper開度_${field.label.replace(/\s*\([^)]*\)$/, "")}`,
    validation: "percentage",
  }));
};

export const allDamperOpeningFields = {
  vt8: createDamperConfig([
    {
      id: "damper_vt8_01",
      dataKey: "damperOpeningData.vt8_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 601,
    },
    {
      id: "damper_vt8_02",
      dataKey: "damperOpeningData.vt8_02",
      label: "② TOP室排氣(右) (%)",
      order: 602,
    },
    {
      id: "damper_vt8_03",
      dataKey: "damperOpeningData.vt8_03",
      label: "③ TOP室排氣(左) (%)",
      order: 603,
    },
    {
      id: "damper_vt8_04",
      dataKey: "damperOpeningData.vt8_04",
      label: "④ 上部AC給氣(主) (%)",
      order: 604,
    },
    {
      id: "damper_vt8_05",
      dataKey: "damperOpeningData.vt8_05",
      label: "⑤ 1室上AC給氣(C) (%)",
      order: 605,
    },
    {
      id: "damper_vt8_06",
      dataKey: "damperOpeningData.vt8_06",
      label: "⑥ 1室上AC給氣(右) (%)",
      order: 606,
    },
    {
      id: "damper_vt8_07",
      dataKey: "damperOpeningData.vt8_07",
      label: "⑦ 1室上AC給氣(左) (%)",
      order: 607,
    },
    {
      id: "damper_vt8_08",
      dataKey: "damperOpeningData.vt8_08",
      label: "⑧ 1室上AC排氣(A) (%)",
      order: 608,
    },
    {
      id: "damper_vt8_09",
      dataKey: "damperOpeningData.vt8_09",
      label: "⑨ 1室上AC排氣(右) (%)",
      order: 609,
    },
    {
      id: "damper_vt8_10",
      dataKey: "damperOpeningData.vt8_10",
      label: "⑩ 1室上AC排氣(左) (%)",
      order: 610,
    },
    {
      id: "damper_vt8_11",
      dataKey: "damperOpeningData.vt8_11",
      label: "⑪ 1室排氣(右) (%)",
      order: 611,
    },
    {
      id: "damper_vt8_12",
      dataKey: "damperOpeningData.vt8_12",
      label: "⑫ 1室排氣(左) (%)",
      order: 612,
    },
    {
      id: "damper_vt8_13",
      dataKey: "damperOpeningData.vt8_13",
      label: "⑬ 2室上AC給氣(D) (%)",
      order: 613,
    },
    {
      id: "damper_vt8_14",
      dataKey: "damperOpeningData.vt8_14",
      label: "⑭ 2室上AC給氣(右) (%)",
      order: 614,
    },
    {
      id: "damper_vt8_15",
      dataKey: "damperOpeningData.vt8_15",
      label: "⑮ 2室上AC給氣(左) (%)",
      order: 615,
    },
    {
      id: "damper_vt8_16",
      dataKey: "damperOpeningData.vt8_16",
      label: "⑯ 2室上AC排氣(B) (%)",
      order: 616,
    },
    {
      id: "damper_vt8_17",
      dataKey: "damperOpeningData.vt8_17",
      label: "⑰ 2室上AC排氣(右) (%)",
      order: 617,
    },
    {
      id: "damper_vt8_18",
      dataKey: "damperOpeningData.vt8_18",
      label: "⑱ 2室上AC排氣(左) (%)",
      order: 618,
    },
    {
      id: "damper_vt8_19",
      dataKey: "damperOpeningData.vt8_19",
      label: "⑲ 2室排氣(右) (%)",
      order: 619,
    },
    {
      id: "damper_vt8_20",
      dataKey: "damperOpeningData.vt8_20",
      label: "⑳ 2室排氣(左) (%)",
      order: 620,
    },
    {
      id: "damper_vt8_21",
      dataKey: "damperOpeningData.vt8_21",
      label: "㉑ 1室外部新鮮空氣 (%)",
      order: 621,
    },
    {
      id: "damper_vt8_22",
      dataKey: "damperOpeningData.vt8_22",
      label: "㉒ 2室外部新鮮空氣 (%)",
      order: 622,
    },
    {
      id: "damper_vt8_23",
      dataKey: "damperOpeningData.vt8_23",
      label: "㉓ 下部AC給氣(主) (%)",
      order: 623,
    },
    {
      id: "damper_vt8_24",
      dataKey: "damperOpeningData.vt8_24",
      label: "㉔ 下部AC排氣FAN (%)",
      order: 624,
    },
    {
      id: "damper_vt8_25",
      dataKey: "damperOpeningData.vt8_25",
      label: "㉕ 1室給氣(右) (%)",
      order: 625,
    },
    {
      id: "damper_vt8_26",
      dataKey: "damperOpeningData.vt8_26",
      label: "㉖ 1室給氣(左) (%)",
      order: 626,
    },
    {
      id: "damper_vt8_27",
      dataKey: "damperOpeningData.vt8_27",
      label: "㉗ 1下部AC排氣(右) (%)",
      order: 627,
    },
    {
      id: "damper_vt8_28",
      dataKey: "damperOpeningData.vt8_28",
      label: "㉘ 1下部AC排氣(左) (%)",
      order: 628,
    },
    {
      id: "damper_vt8_29",
      dataKey: "damperOpeningData.vt8_29",
      label: "㉙ 1下部AC給氣(右) (%)",
      order: 629,
    },
    {
      id: "damper_vt8_30",
      dataKey: "damperOpeningData.vt8_30",
      label: "㉚ 1下部AC給氣(左) (%)",
      order: 630,
    },
    {
      id: "damper_vt8_31",
      dataKey: "damperOpeningData.vt8_31",
      label: "㉛ 2室給氣(右) (%)",
      order: 631,
    },
    {
      id: "damper_vt8_32",
      dataKey: "damperOpeningData.vt8_32",
      label: "㉜ 2室給氣(左) (%)",
      order: 632,
    },
    {
      id: "damper_vt8_33",
      dataKey: "damperOpeningData.vt8_33",
      label: "㉝ 2下部AC排氣(右) (%)",
      order: 633,
    },
    {
      id: "damper_vt8_34",
      dataKey: "damperOpeningData.vt8_34",
      label: "㉞ 2下部AC排氣(左) (%)",
      order: 634,
    },
    {
      id: "damper_vt8_35",
      dataKey: "damperOpeningData.vt8_35",
      label: "㉟ 2下部AC給氣(右) (%)",
      order: 635,
    },
    {
      id: "damper_vt8_36",
      dataKey: "damperOpeningData.vt8_36",
      label: "㊱ 2下部AC給氣(左) (%)",
      order: 636,
    },
    {
      id: "damper_vt8_37",
      dataKey: "damperOpeningData.vt8_37",
      label: "㊲ 1室下AC給氣(副) (%)",
      order: 637,
    },
    {
      id: "damper_vt8_38",
      dataKey: "damperOpeningData.vt8_38",
      label: "㊳ 2室下AC給氣(副) (%)",
      order: 638,
    },
  ]),
  vt7: createDamperConfig([
    {
      id: "damper_vt7_01",
      dataKey: "damperOpeningData.vt7_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 701,
    },
    {
      id: "damper_vt7_02",
      dataKey: "damperOpeningData.vt7_02",
      label: "② TOP室排氣(右) (%)",
      order: 702,
    },
    {
      id: "damper_vt7_03",
      dataKey: "damperOpeningData.vt7_03",
      label: "③ TOP室排氣(左) (%)",
      order: 703,
    },
    {
      id: "damper_vt7_04",
      dataKey: "damperOpeningData.vt7_04",
      label: "④ 1室上AC給氣(上) (%)",
      order: 704,
    },
    {
      id: "damper_vt7_05",
      dataKey: "damperOpeningData.vt7_05",
      label: "⑤ 1室上AC給氣(下) (%)",
      order: 705,
    },
    {
      id: "damper_vt7_06",
      dataKey: "damperOpeningData.vt7_06",
      label: "⑥ 1室上AC排氣(右) (%)",
      order: 706,
    },
    {
      id: "damper_vt7_07",
      dataKey: "damperOpeningData.vt7_07",
      label: "⑦ 1室上AC排氣(左) (%)",
      order: 707,
    },
    {
      id: "damper_vt7_08",
      dataKey: "damperOpeningData.vt7_08",
      label: "⑧ 1室給氣(右) (%)",
      order: 708,
    },
    {
      id: "damper_vt7_09",
      dataKey: "damperOpeningData.vt7_09",
      label: "⑨ 1室給氣(左) (%)",
      order: 709,
    },
    {
      id: "damper_vt7_10",
      dataKey: "damperOpeningData.vt7_10",
      label: "⑩ 2室上AC給氣 (%)",
      order: 710,
    },
    {
      id: "damper_vt7_11",
      dataKey: "damperOpeningData.vt7_11",
      label: "⑪ 2室上AC排氣(左) (%)",
      order: 711,
    },
    {
      id: "damper_vt7_12",
      dataKey: "damperOpeningData.vt7_12",
      label: "⑫ 2室上AC排氣(右) (%)",
      order: 712,
    },
    {
      id: "damper_vt7_14",
      dataKey: "damperOpeningData.vt7_14",
      label: "⑭ 2室給氣(右) (%)",
      order: 714,
    },
    {
      id: "damper_vt7_15",
      dataKey: "damperOpeningData.vt7_15",
      label: "⑮ 2室給氣(左) (%)",
      order: 715,
    },
    {
      id: "damper_vt7_16",
      dataKey: "damperOpeningData.vt7_16",
      label: "⑯ 上部AC給氣(主) (%)",
      order: 716,
    },
    {
      id: "damper_vt7_17",
      dataKey: "damperOpeningData.vt7_17",
      label: "⑰ 下部AC給氣 (%)",
      order: 717,
    },
    {
      id: "damper_vt7_18",
      dataKey: "damperOpeningData.vt7_18",
      label: "⑱ 下部AC排氣 (%)",
      order: 718,
    },
    {
      id: "damper_vt7_19",
      dataKey: "damperOpeningData.vt7_19",
      label: "⑲ 1室排氣(左) (%)",
      order: 719,
    },
    {
      id: "damper_vt7_20",
      dataKey: "damperOpeningData.vt7_20",
      label: "⑳ 1室排氣(右) (%)",
      order: 720,
    },
    {
      id: "damper_vt7_21",
      dataKey: "damperOpeningData.vt7_21",
      label: "㉑ 1下部AC給氣(左) (%)",
      order: 721,
    },
    {
      id: "damper_vt7_22",
      dataKey: "damperOpeningData.vt7_22",
      label: "㉒ 1下部AC給氣(右) (%)",
      order: 722,
    },
    {
      id: "damper_vt7_23",
      dataKey: "damperOpeningData.vt7_23",
      label: "㉓ 2室排氣(左) (%)",
      order: 723,
    },
    {
      id: "damper_vt7_24",
      dataKey: "damperOpeningData.vt7_24",
      label: "㉔ 2室排氣(右) (%)",
      order: 724,
    },
    {
      id: "damper_vt7_25",
      dataKey: "damperOpeningData.vt7_25",
      label: "㉕ 2下部AC排氣(右) (%)",
      order: 725,
    },
    {
      id: "damper_vt7_26",
      dataKey: "damperOpeningData.vt7_26",
      label: "㉖ 2下部AC排氣(左) (%)",
      order: 726,
    },
    {
      id: "damper_vt7_27",
      dataKey: "damperOpeningData.vt7_27",
      label: "㉗ 2下部AC給氣(左) (%)",
      order: 727,
    },
    {
      id: "damper_vt7_28",
      dataKey: "damperOpeningData.vt7_28",
      label: "㉘ 2下部AC給氣(右) (%)",
      order: 728,
    },
    {
      id: "damper_vt7_29",
      dataKey: "damperOpeningData.vt7_29",
      label: "㉙ 下AC給氣(1室側) (%)",
      order: 729,
    },
    {
      id: "damper_vt7_30",
      dataKey: "damperOpeningData.vt7_30",
      label: "㉚ 下AC給氣(2室側) (%)",
      order: 730,
    },
    {
      id: "damper_vt7_31",
      dataKey: "damperOpeningData.vt7_31",
      label: "㉛ 1室外部新鮮空氣 (%)",
      order: 731,
    },
    {
      id: "damper_vt7_32",
      dataKey: "damperOpeningData.vt7_32",
      label: "㉜ 2室外部新鮮空氣 (%)",
      order: 732,
    },
    {
      id: "damper_vt7_34",
      dataKey: "damperOpeningData.vt7_34",
      label: "㉞ 1室給氣HEPA (%)",
      order: 734,
    },
    {
      id: "damper_vt7_35",
      dataKey: "damperOpeningData.vt7_35",
      label: "㉟ 2室給氣HEPA (%)",
      order: 735,
    },
  ]),
  vt6: createDamperConfig([
    {
      id: "damper_vt6_01",
      dataKey: "damperOpeningData.vt6_01",
      label: "① 上部AC排氣FAN (%)",
      order: 901,
    },
    {
      id: "damper_vt6_02",
      dataKey: "damperOpeningData.vt6_02",
      label: "② TOP室排氣(右) (%)",
      order: 902,
    },
    {
      id: "damper_vt6_03",
      dataKey: "damperOpeningData.vt6_03",
      label: "③ TOP室排氣(左) (%)",
      order: 903,
    },
    {
      id: "damper_vt6_04",
      dataKey: "damperOpeningData.vt6_04",
      label: "④ 1室上AC給氣(上) (%)",
      order: 904,
    },
    {
      id: "damper_vt6_05",
      dataKey: "damperOpeningData.vt6_05",
      label: "⑤ 1室上AC給氣(下) (%)",
      order: 905,
    },
    {
      id: "damper_vt6_06",
      dataKey: "damperOpeningData.vt6_06",
      label: "⑥ 1室上AC排氣(上右) (%)",
      order: 906,
    },
    {
      id: "damper_vt6_07",
      dataKey: "damperOpeningData.vt6_07",
      label: "⑦ 1室上AC排氣(上左) (%)",
      order: 907,
    },
    {
      id: "damper_vt6_08",
      dataKey: "damperOpeningData.vt6_08",
      label: "⑧ 1室上AC排氣(中右) (%)",
      order: 908,
    },
    {
      id: "damper_vt6_09",
      dataKey: "damperOpeningData.vt6_09",
      label: "⑨ 1室上AC排氣(中左) (%)",
      order: 909,
    },
    {
      id: "damper_vt6_10",
      dataKey: "damperOpeningData.vt6_10",
      label: "⑩ 1室上AC排氣(下右) (%)",
      order: 910,
    },
    {
      id: "damper_vt6_11",
      dataKey: "damperOpeningData.vt6_11",
      label: "⑪ 1室上AC排氣(下左) (%)",
      order: 911,
    },
    {
      id: "damper_vt6_12",
      dataKey: "damperOpeningData.vt6_12",
      label: "⑫ 1室給氣(右) (%)",
      order: 912,
    },
    {
      id: "damper_vt6_13",
      dataKey: "damperOpeningData.vt6_13",
      label: "⑬ 1室給氣(左) (%)",
      order: 913,
    },
    {
      id: "damper_vt6_14",
      dataKey: "damperOpeningData.vt6_14",
      label: "⑭ 2室上AC給氣 (%)",
      order: 914,
    },
    {
      id: "damper_vt6_15",
      dataKey: "damperOpeningData.vt6_15",
      label: "⑮ 2室上AC排氣(右) (%)",
      order: 915,
    },
    {
      id: "damper_vt6_16",
      dataKey: "damperOpeningData.vt6_16",
      label: "⑯ 2室上AC排氣(左) (%)",
      order: 916,
    },
    {
      id: "damper_vt6_17",
      dataKey: "damperOpeningData.vt6_17",
      label: "⑰ 2室給氣(右) (%)",
      order: 917,
    },
    {
      id: "damper_vt6_18",
      dataKey: "damperOpeningData.vt6_18",
      label: "⑱ 2室給氣(左) (%)",
      order: 918,
    },
    {
      id: "damper_vt6_19",
      dataKey: "damperOpeningData.vt6_19",
      label: "⑲ 上部AC給氣(主) (%)",
      order: 919,
    },
    {
      id: "damper_vt6_20",
      dataKey: "damperOpeningData.vt6_20",
      label: "⑳ 1室外部新鮮空氣 (%)",
      order: 920,
    },
    {
      id: "damper_vt6_21",
      dataKey: "damperOpeningData.vt6_21",
      label: "㉑ 2室外部新鮮空氣 (%)",
      order: 921,
    },
    {
      id: "damper_vt6_22",
      dataKey: "damperOpeningData.vt6_22",
      label: "㉒ 下部AC給氣 (%)",
      order: 922,
    },
    {
      id: "damper_vt6_23",
      dataKey: "damperOpeningData.vt6_23",
      label: "㉓ 下部AC排氣 (%)",
      order: 923,
    },
    {
      id: "damper_vt6_24",
      dataKey: "damperOpeningData.vt6_24",
      label: "㉔ 1室排氣(右) (%)",
      order: 924,
    },
    {
      id: "damper_vt6_25",
      dataKey: "damperOpeningData.vt6_25",
      label: "㉕ 1室排氣(左) (%)",
      order: 925,
    },
    {
      id: "damper_vt6_26",
      dataKey: "damperOpeningData.vt6_26",
      label: "㉖ 1下部AC給氣(右) (%)",
      order: 926,
    },
    {
      id: "damper_vt6_27",
      dataKey: "damperOpeningData.vt6_27",
      label: "㉗ 1下部AC給氣(左) (%)",
      order: 927,
    },
    {
      id: "damper_vt6_28",
      dataKey: "damperOpeningData.vt6_28",
      label: "㉘ 1下部AC給氣(副) (%)",
      order: 928,
    },
    {
      id: "damper_vt6_29",
      dataKey: "damperOpeningData.vt6_29",
      label: "㉙ 2室排氣(右) (%)",
      order: 929,
    },
    {
      id: "damper_vt6_30",
      dataKey: "damperOpeningData.vt6_30",
      label: "㉚ 2室排氣(左) (%)",
      order: 930,
    },
    {
      id: "damper_vt6_31",
      dataKey: "damperOpeningData.vt6_31",
      label: "㉛ 2下部AC排氣(右) (%)",
      order: 931,
    },
    {
      id: "damper_vt6_32",
      dataKey: "damperOpeningData.vt6_32",
      label: "㉜ 2下部AC排氣(左) (%)",
      order: 932,
    },
    {
      id: "damper_vt6_33",
      dataKey: "damperOpeningData.vt6_33",
      label: "㉝ 2下部AC給氣(右) (%)",
      order: 933,
    },
    {
      id: "damper_vt6_34",
      dataKey: "damperOpeningData.vt6_34",
      label: "㉞ 2下部AC給氣(左) (%)",
      order: 934,
    },
    {
      id: "damper_vt6_35",
      dataKey: "damperOpeningData.vt6_35",
      label: "㉟ 1室給氣HEPA (%)",
      order: 935,
    },
    {
      id: "damper_vt6_36",
      dataKey: "damperOpeningData.vt6_36",
      label: "㊱ 2室給氣HEPA (%)",
      order: 936,
    },
    {
      id: "damper_vt6_37",
      dataKey: "damperOpeningData.vt6_37",
      label: "㊲ 2下部AC給氣(副) (%)",
      order: 937,
    },
    {
      id: "damper_vt6_38",
      dataKey: "damperOpeningData.vt6_38",
      label: "㊳ 1室排氣風管(主) (%)",
      order: 938,
    },
    {
      id: "damper_vt6_39",
      dataKey: "damperOpeningData.vt6_39",
      label: "㊴ 2室排氣風管(主) (%)",
      order: 939,
    },
  ]),
  vt5: createDamperConfig([
    {
      id: "damper_vt5_01",
      dataKey: "damperOpeningData.vt5_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 801,
    },
    {
      id: "damper_vt5_02",
      dataKey: "damperOpeningData.vt5_02",
      label: "② TOP室排氣(右) (%)",
      order: 802,
    },
    {
      id: "damper_vt5_03",
      dataKey: "damperOpeningData.vt5_03",
      label: "③ TOP室排氣(左) (%)",
      order: 803,
    },
    {
      id: "damper_vt5_04",
      dataKey: "damperOpeningData.vt5_04",
      label: "④ 上部AC給氣(主) (%)",
      order: 804,
    },
    {
      id: "damper_vt5_05",
      dataKey: "damperOpeningData.vt5_05",
      label: "⑤ 1室上AC給氣(C) (%)",
      order: 805,
    },
    {
      id: "damper_vt5_06",
      dataKey: "damperOpeningData.vt5_06",
      label: "⑥ 1室上AC給氣(右) (%)",
      order: 806,
    },
    {
      id: "damper_vt5_07",
      dataKey: "damperOpeningData.vt5_07",
      label: "⑦ 1室上AC給氣(左) (%)",
      order: 807,
    },
    {
      id: "damper_vt5_08",
      dataKey: "damperOpeningData.vt5_08",
      label: "⑧ 1室上AC排氣(A) (%)",
      order: 808,
    },
    {
      id: "damper_vt5_09",
      dataKey: "damperOpeningData.vt5_09",
      label: "⑨ 1室上AC排氣(右) (%)",
      order: 809,
    },
    {
      id: "damper_vt5_10",
      dataKey: "damperOpeningData.vt5_10",
      label: "⑩ 1室上AC排氣(左) (%)",
      order: 810,
    },
    {
      id: "damper_vt5_11",
      dataKey: "damperOpeningData.vt5_11",
      label: "⑪ 1室給氣(右) (%)",
      order: 811,
    },
    {
      id: "damper_vt5_12",
      dataKey: "damperOpeningData.vt5_12",
      label: "⑫ 1室給氣(左) (%)",
      order: 812,
    },
    {
      id: "damper_vt5_13",
      dataKey: "damperOpeningData.vt5_13",
      label: "⑬ 2室上AC給氣(D) (%)",
      order: 813,
    },
    {
      id: "damper_vt5_14",
      dataKey: "damperOpeningData.vt5_14",
      label: "⑭ 2室上AC給氣(右) (%)",
      order: 814,
    },
    {
      id: "damper_vt5_15",
      dataKey: "damperOpeningData.vt5_15",
      label: "⑮ 2室上AC給氣(左) (%)",
      order: 815,
    },
    {
      id: "damper_vt5_16",
      dataKey: "damperOpeningData.vt5_16",
      label: "⑯ 2室上AC排氣(B) (%)",
      order: 816,
    },
    {
      id: "damper_vt5_17",
      dataKey: "damperOpeningData.vt5_17",
      label: "⑰ 2室上AC排氣(右) (%)",
      order: 817,
    },
    {
      id: "damper_vt5_18",
      dataKey: "damperOpeningData.vt5_18",
      label: "⑱ 2室上AC排氣(左) (%)",
      order: 818,
    },
    {
      id: "damper_vt5_19",
      dataKey: "damperOpeningData.vt5_19",
      label: "⑲ 2室給氣(右) (%)",
      order: 819,
    },
    {
      id: "damper_vt5_20",
      dataKey: "damperOpeningData.vt5_20",
      label: "⑳ 2室給氣(左) (%)",
      order: 820,
    },
    {
      id: "damper_vt5_21",
      dataKey: "damperOpeningData.vt5_21",
      label: "㉑ 1室外部新鮮空氣 (%)",
      order: 821,
    },
    {
      id: "damper_vt5_22",
      dataKey: "damperOpeningData.vt5_22",
      label: "㉒ 2室外部新鮮空氣 (%)",
      order: 822,
    },
    {
      id: "damper_vt5_23",
      dataKey: "damperOpeningData.vt5_23",
      label: "㉓ 下部AC給氣(主) (%)",
      order: 823,
    },
    {
      id: "damper_vt5_24",
      dataKey: "damperOpeningData.vt5_24",
      label: "㉔ 下部AC排氣FAN (%)",
      order: 824,
    },
    {
      id: "damper_vt5_25",
      dataKey: "damperOpeningData.vt5_25",
      label: "㉕ 1室排氣(右) (%)",
      order: 825,
    },
    {
      id: "damper_vt5_26",
      dataKey: "damperOpeningData.vt5_26",
      label: "㉖ 1室排氣(左) (%)",
      order: 826,
    },
    {
      id: "damper_vt5_27",
      dataKey: "damperOpeningData.vt5_27",
      label: "㉗ 1下部AC排氣(右) (%)",
      order: 827,
    },
    {
      id: "damper_vt5_28",
      dataKey: "damperOpeningData.vt5_28",
      label: "㉘ 1下部AC排氣(左) (%)",
      order: 828,
    },
    {
      id: "damper_vt5_29",
      dataKey: "damperOpeningData.vt5_29",
      label: "㉙ 1下部AC給氣(右) (%)",
      order: 829,
    },
    {
      id: "damper_vt5_30",
      dataKey: "damperOpeningData.vt5_30",
      label: "㉚ 1下部AC給氣(左) (%)",
      order: 830,
    },
    {
      id: "damper_vt5_31",
      dataKey: "damperOpeningData.vt5_31",
      label: "㉛ 2室排氣(右) (%)",
      order: 831,
    },
    {
      id: "damper_vt5_32",
      dataKey: "damperOpeningData.vt5_32",
      label: "㉜ 2室排氣(左) (%)",
      order: 832,
    },
    {
      id: "damper_vt5_33",
      dataKey: "damperOpeningData.vt5_33",
      label: "㉝ 2下部AC排氣(右) (%)",
      order: 833,
    },
    {
      id: "damper_vt5_34",
      dataKey: "damperOpeningData.vt5_34",
      label: "㉞ 2下部AC排氣(左) (%)",
      order: 834,
    },
    {
      id: "damper_vt5_35",
      dataKey: "damperOpeningData.vt5_35",
      label: "㉟ 2下部AC給氣(右) (%)",
      order: 835,
    },
    {
      id: "damper_vt5_36",
      dataKey: "damperOpeningData.vt5_36",
      label: "㊱ 2下部AC給氣(左) (%)",
      order: 836,
    },
    {
      id: "damper_vt5_37",
      dataKey: "damperOpeningData.vt5_37",
      label: "㊲ 1室下AC給氣(副) (%)",
      order: 837,
    },
    {
      id: "damper_vt5_38",
      dataKey: "damperOpeningData.vt5_38",
      label: "㊳ 2室下AC給氣(副) (%)",
      order: 838,
    },
  ]),
  vt1: createDamperConfig([
    {
      id: "damper_vt1_01",
      dataKey: "damperOpeningData.vt1_01",
      label: "① TOP室排氣(右) (%)",
      order: 1001,
    },
    {
      id: "damper_vt1_02",
      dataKey: "damperOpeningData.vt1_02",
      label: "② TOP室排氣(左) (%)",
      order: 1002,
    },
    {
      id: "damper_vt1_03",
      dataKey: "damperOpeningData.vt1_03",
      label: "③ 1室上AC給氣(右) (%)",
      order: 1003,
    },
    {
      id: "damper_vt1_04",
      dataKey: "damperOpeningData.vt1_04",
      label: "④ 1室上AC給氣(左) (%)",
      order: 1004,
    },
    {
      id: "damper_vt1_05",
      dataKey: "damperOpeningData.vt1_05",
      label: "⑤ 1室上AC排氣(右) (%)",
      order: 1005,
    },
    {
      id: "damper_vt1_06",
      dataKey: "damperOpeningData.vt1_06",
      label: "⑥ 1室上AC排氣(左) (%)",
      order: 1006,
    },
    {
      id: "damper_vt1_07",
      dataKey: "damperOpeningData.vt1_07",
      label: "⑦ 1室給氣(右) (%)",
      order: 1007,
    },
    {
      id: "damper_vt1_08",
      dataKey: "damperOpeningData.vt1_08",
      label: "⑧ 1室給氣(左) (%)",
      order: 1008,
    },
    {
      id: "damper_vt1_09",
      dataKey: "damperOpeningData.vt1_09",
      label: "⑨ 2室上AC給氣(右) (%)",
      order: 1009,
    },
    {
      id: "damper_vt1_10",
      dataKey: "damperOpeningData.vt1_10",
      label: "⑩ 2室上AC給氣(左) (%)",
      order: 1010,
    },
    {
      id: "damper_vt1_11",
      dataKey: "damperOpeningData.vt1_11",
      label: "⑪ 2室上AC排氣(右) (%)",
      order: 1011,
    },
    {
      id: "damper_vt1_12",
      dataKey: "damperOpeningData.vt1_12",
      label: "⑫ 2室上AC排氣(左) (%)",
      order: 1012,
    },
    {
      id: "damper_vt1_13",
      dataKey: "damperOpeningData.vt1_13",
      label: "⑬ 2室給氣(右) (%)",
      order: 1013,
    },
    {
      id: "damper_vt1_14",
      dataKey: "damperOpeningData.vt1_14",
      label: "⑭ 2室給氣(左) (%)",
      order: 1014,
    },
    {
      id: "damper_vt1_15",
      dataKey: "damperOpeningData.vt1_15",
      label: "⑮ 1室外部新鮮空氣 (%)",
      order: 1015,
    },
    {
      id: "damper_vt1_16",
      dataKey: "damperOpeningData.vt1_16",
      label: "⑯ 1室給氣(含浸室) (%)",
      order: 1016,
    },
    {
      id: "damper_vt1_17",
      dataKey: "damperOpeningData.vt1_17",
      label: "⑰ 2室外部新鮮空氣 (%)",
      order: 1017,
    },
    {
      id: "damper_vt1_18",
      dataKey: "damperOpeningData.vt1_18",
      label: "⑱ 2室給氣(含浸室) (%)",
      order: 1018,
    },
    {
      id: "damper_vt1_19",
      dataKey: "damperOpeningData.vt1_19",
      label: "⑲ 下部AC進氣 (%)",
      order: 1019,
    },
    {
      id: "damper_vt1_20",
      dataKey: "damperOpeningData.vt1_20",
      label: "⑳ 下部AC給氣 (%)",
      order: 1020,
    },
    {
      id: "damper_vt1_21",
      dataKey: "damperOpeningData.vt1_21",
      label: "㉑ 下部AC排氣 (%)",
      order: 1021,
    },
    {
      id: "damper_vt1_22",
      dataKey: "damperOpeningData.vt1_22",
      label: "㉒ 1室排氣(右) (%)",
      order: 1022,
    },
    {
      id: "damper_vt1_23",
      dataKey: "damperOpeningData.vt1_23",
      label: "㉓ 1室排氣(左) (%)",
      order: 1023,
    },
    {
      id: "damper_vt1_24",
      dataKey: "damperOpeningData.vt1_24",
      label: "㉔ 1下部AC排氣(右) (%)",
      order: 1024,
    },
    {
      id: "damper_vt1_25",
      dataKey: "damperOpeningData.vt1_25",
      label: "㉕ 1下部AC排氣(左) (%)",
      order: 1025,
    },
    {
      id: "damper_vt1_26",
      dataKey: "damperOpeningData.vt1_26",
      label: "㉖ 1下部AC給氣(右) (%)",
      order: 1026,
    },
    {
      id: "damper_vt1_27",
      dataKey: "damperOpeningData.vt1_27",
      label: "㉗ 1下部AC給氣(左) (%)",
      order: 1027,
    },
    {
      id: "damper_vt1_28",
      dataKey: "damperOpeningData.vt1_28",
      label: "㉘ 2室排氣(右) (%)",
      order: 1028,
    },
    {
      id: "damper_vt1_29",
      dataKey: "damperOpeningData.vt1_29",
      label: "㉙ 2室排氣(左) (%)",
      order: 1029,
    },
    {
      id: "damper_vt1_30",
      dataKey: "damperOpeningData.vt1_30",
      label: "㉚ 2下部AC排氣(右) (%)",
      order: 1030,
    },
    {
      id: "damper_vt1_31",
      dataKey: "damperOpeningData.vt1_31",
      label: "㉛ 2下部AC排氣(左) (%)",
      order: 1031,
    },
    {
      id: "damper_vt1_32",
      dataKey: "damperOpeningData.vt1_32",
      label: "㉜ 2下部AC給氣(右) (%)",
      order: 1032,
    },
    {
      id: "damper_vt1_33",
      dataKey: "damperOpeningData.vt1_33",
      label: "㉝ 2下部AC給氣(左) (%)",
      order: 1033,
    },
    {
      id: "damper_vt1_34",
      dataKey: "damperOpeningData.vt1_34",
      label: "㉞ 含浸室排氣(右) (%)",
      order: 1034,
    },
    {
      id: "damper_vt1_35",
      dataKey: "damperOpeningData.vt1_35",
      label: "㉟ 含浸室排氣(左) (%)",
      order: 1035,
    },
    {
      id: "damper_vt1_36",
      dataKey: "damperOpeningData.vt1_36",
      label: "㊱ 含浸室新鮮給氣 (%)",
      order: 1036,
    },
    {
      id: "damper_vt1_37",
      dataKey: "damperOpeningData.vt1_37",
      label: "㊲ 1室給氣HEPA (%)",
      order: 1037,
    },
    {
      id: "damper_vt1_38",
      dataKey: "damperOpeningData.vt1_38",
      label: "㊳ 2室給氣HEPA (%)",
      order: 1038,
    },
    {
      id: "damper_vt1_39",
      dataKey: "damperOpeningData.vt1_39",
      label: "㊴ 上部AC給氣HEPA (%)",
      order: 1039,
    },
    {
      id: "damper_vt1_40",
      dataKey: "damperOpeningData.vt1_40",
      label: "㊵ 下部AC給氣HEPA (%)",
      order: 1040,
    },
    {
      id: "damper_vt1_41",
      dataKey: "damperOpeningData.vt1_41",
      label: "㊶ 上部AC給氣(主) (%)",
      order: 1041,
    },
  ]),
};

// 5. 技術溫測點設定
export const techTempPoints = [
  ...Array.from({ length: 11 }, (_, i) => ({
    id: `${i + 1}`,
    label: `技術溫測實溫_${i + 1}`,
    orderOffset: 200 + i * 10,
  })),
  { id: "T1", label: "技術溫測實溫_T1", orderOffset: 200 + 11 * 10 },
  { id: "T2", label: "技術溫測實溫_T2", orderOffset: 200 + 12 * 10 },
  ...Array.from({ length: 11 }, (_, i) => ({
    id: `${i + 12}`,
    label: `技術溫測實溫_${i + 12}`,
    orderOffset: 200 + (13 + i) * 10,
  })),
];
