// /js/modules/config.js (已拆分)
// 這個檔案現在是設定的中心樞紐，負責組合和匯出所有設定。

import { hmiLayouts, hmiFieldsByModel } from "./config/hmi.js";
import {
  damperLayoutsByModel,
  allDryerAirVolumeMeasurements,
  getAirVolumeMeasurementsByModel,
  allDamperOpeningFields,
  techTempPoints,
} from "./config/measurements.js";

// -------------------------------------------------------------------
// 基礎設定 (保留在此處)
// -------------------------------------------------------------------
const LOCAL_STORAGE_KEY = "dryerRecords";

// -------------------------------------------------------------------
// ▼▼▼ 主要的欄位設定生成函式 (唯一的核心函式) ▼▼▼
// -------------------------------------------------------------------
const generateFieldConfigurations = (currentDryerModel = "vt8") => {
  // 1. 基本資訊 (所有模式通用)
  const baseFields = [
    {
      id: "recordTypeDisplay",
      dataKey: "recordType",
      isHeader: true,
      label: "類型",
      csvHeader: "類型",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "display",
      order: 1,
      inTable: true,
    },
    {
      id: "dryerModelDisplay",
      dataKey: "dryerModel",
      isHeader: true,
      label: "機台型號",
      csvHeader: "機台型號",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "display",
      order: 2,
      inTable: true,
    },
    {
      id: "rtoStatus",
      dataKey: "rtoStatus",
      label: "RTO啟用狀態",
      csvHeader: "RTO啟用狀態",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "radio",
      order: 2.5,
      inTable: true,
    },
    {
      id: "heatingStatus",
      dataKey: "heatingStatus",
      label: "升溫啟用狀態",
      csvHeader: "升溫狀態",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "radio",
      order: 2.6,
      inTable: true,
    },
    {
      id: "dateTime",
      dataKey: "dateTime",
      isHeader: true,
      label: "記錄日期時間",
      csvHeader: "日期時間",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "datetime-local",
      required: true,
      order: 2.1,
      inTable: true,
    },
    {
      id: "remark",
      dataKey: "remark",
      isHeader: true,
      label: "備註",
      csvHeader: "備註",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "textarea",
      order: 4,
      inTable: true,
    },
  ];

  // 2. 評價 TEAM 專用欄位
  const recorder1Fields = [
    {
      id: "recorder1_chamber1_lower",
      dataKey: "recorder1Data.chamber1_lower",
      label: "實測第一紀錄器_1室下 (℃)",
      csvHeader: "實測第一紀錄器_1室下 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 11,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper",
      dataKey: "recorder1Data.chamber1_upper",
      label: "實測第一紀錄器_1室上 (℃)",
      csvHeader: "實測第一紀錄器_1室上 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 12,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_supply",
      dataKey: "recorder1Data.chamber1_supply",
      label: "實測第一紀錄器_1室給氣 (℃)",
      csvHeader: "實測第一紀錄器_1室給氣 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 13,
      inTable: true,
    },
    {
      id: "recorder1_chamber2_supply",
      dataKey: "recorder1Data.chamber2_supply",
      label: "實測第一紀錄器_2室給氣 (℃)",
      csvHeader: "實測第一紀錄器_2室給氣 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 14,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_right",
      dataKey: "recorder1Data.chamber1_lower_right",
      label: "實測第一紀錄器_1下右 (℃)",
      csvHeader: "實測第一紀錄器_1下右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 15,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_middle",
      dataKey: "recorder1Data.chamber1_lower_middle",
      label: "實測第一紀錄器_1下中 (℃)",
      csvHeader: "實測第一紀錄器_1下中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 16,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_left",
      dataKey: "recorder1Data.chamber1_lower_left",
      label: "實測第一紀錄器_1下左 (℃)",
      csvHeader: "實測第一紀錄器_1下左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 17,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_middle_middle",
      dataKey: "recorder1Data.chamber1_middle_middle",
      label: "實測第一紀錄器_1中中 (℃)",
      csvHeader: "實測第一紀錄器_1中中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 18,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_right",
      dataKey: "recorder1Data.chamber1_upper_right",
      label: "實測第一紀錄器_1上右 (℃)",
      csvHeader: "實測第一紀錄器_1上右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 19,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_middle",
      dataKey: "recorder1Data.chamber1_upper_middle",
      label: "實測第一紀錄器_1上中 (℃)",
      csvHeader: "實測第一紀錄器_1上中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 20,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_left",
      dataKey: "recorder1Data.chamber1_upper_left",
      label: "實測第一紀錄器_1上左 (℃)",
      csvHeader: "實測第一紀錄器_1上左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 21,
      inTable: true,
    },
  ];
  const recorder2Fields = [
    {
      id: "recorder2_chamber2_upper_right",
      dataKey: "recorder2Data.chamber2_upper_right",
      label: "實測第二紀錄器_2上右 (℃)",
      csvHeader: "實測第二紀錄器_2上右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 22,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_upper_middle",
      dataKey: "recorder2Data.chamber2_upper_middle",
      label: "實測第二紀錄器_2上中 (℃)",
      csvHeader: "實測第二紀錄器_2上中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 23,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_upper_left",
      dataKey: "recorder2Data.chamber2_upper_left",
      label: "實測第二紀錄器_2上左 (℃)",
      csvHeader: "實測第二紀錄器_2上左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 24,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_right",
      dataKey: "recorder2Data.chamber2_room_right",
      label: "實測第二紀錄器_2室右 (℃)",
      csvHeader: "實測第二紀錄器_2室右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 25,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_middle",
      dataKey: "recorder2Data.chamber2_room_middle",
      label: "實測第二紀錄器_2室中 (℃)",
      csvHeader: "實測第二紀錄器_2室中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 26,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_left",
      dataKey: "recorder2Data.chamber2_room_left",
      label: "實測第二紀錄器_2室左 (℃)",
      csvHeader: "實測第二紀錄器_2室左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 27,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_middle_middle",
      dataKey: "recorder2Data.chamber2_middle_middle",
      label: "實測第二紀錄器_2中中 (℃)",
      csvHeader: "實測第二紀錄器_2中中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 28,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_right",
      dataKey: "recorder2Data.chamber2_lower_right",
      label: "實測第二紀錄器_2下右 (℃)",
      csvHeader: "實測第二紀錄器_2下右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 29,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_middle",
      dataKey: "recorder2Data.chamber2_lower_middle",
      label: "實測第二紀錄器_2下中 (℃)",
      csvHeader: "實測第二紀錄器_2下中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 30,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_left",
      dataKey: "recorder2Data.chamber2_lower_left",
      label: "實測第二紀錄器_2下左 (℃)",
      csvHeader: "實測第二紀錄器_2下左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 31,
      inTable: true,
    },
  ];

  const airAndExternalFields =
    getAirAndExternalFieldsByModel(currentDryerModel);
  const airVolumeGeneratedFields = [];
  getAirVolumeMeasurementsByModel(currentDryerModel).forEach((measure) => {
    const csvHeaderPrefix = `${currentDryerModel.toUpperCase()}_${
      measure.label
    }`;
    if (measure.status === "normal") {
      airVolumeGeneratedFields.push(
        {
          id: `air_speed_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.speed`,
          label: `${measure.label}_風速(m/s)`,
          csvHeader: `${csvHeaderPrefix}_風速(m/s)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeInput",
          elemType: "number",
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.1,
          inTable: true,
        },
        {
          id: `air_temp_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.temp`,
          label: `${measure.label}_溫度(℃)`,
          csvHeader: `${csvHeaderPrefix}_溫度(℃)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeInput",
          elemType: "number",
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.2,
          inTable: true,
        },
        {
          id: `air_volume_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.volume`,
          label: `${measure.label}_風量(Nm³/分)`,
          csvHeader: `${csvHeaderPrefix}_風量(Nm³/分)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeDisplay",
          elemType: "calculatedText",
          isCalculated: true,
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.3,
          inTable: true,
        }
      );
    } else {
      airVolumeGeneratedFields.push({
        id: `air_status_${currentDryerModel}_${measure.id}`,
        dataKey: `airVolumes.${measure.id}.status`,
        label: `${measure.label}_狀態`,
        csvHeader: `${csvHeaderPrefix}_狀態`,
        recordTypes: ["evaluationTeam"],
        group: "airVolumeInput",
        elemType: "displayStatus",
        isDynamicInput: true,
        parentId: "airVolumeGrid",
        order: measure.order + 0.1,
        inTable: true,
        displayValue: measure.status,
      });
    }
  });

  const techTempGeneratedFields = [];
  techTempPoints.forEach((point) => {
    const recordPointKey = `point${
      point.id.startsWith("T") ? point.id : parseInt(point.id)
    }`;
    const baseLabel = point.label.replace("技術溫測實溫_", "");
    const baseOrder = point.orderOffset;
    for (let i = 1; i <= 5; i++) {
      techTempGeneratedFields.push({
        id: `techTemp_${point.id}_${i}`,
        dataKey: `actualTemps.${recordPointKey}.val${i}`,
        label: `${point.label}.${i}(℃)`,
        csvHeader: `${baseLabel}.${i}(℃)`,
        recordTypes: ["evaluationTeam"],
        group: "techTempInput",
        elemType: "number",
        isDynamicInput: true,
        parentId: "techTempGrid",
        order: baseOrder + i,
        inTable: true,
      });
    }
    techTempGeneratedFields.push({
      id: `techTemp_${point.id}_diff`,
      dataKey: `actualTemps.${recordPointKey}.diff`,
      label: `${point.label}.溫差(℃)`,
      csvHeader: `${baseLabel}.溫差(℃)`,
      recordTypes: ["evaluationTeam"],
      group: "techTempDisplay",
      elemType: "calculatedText",
      isCalculated: true,
      isDynamicInput: true,
      parentId: "techTempGrid",
      order: baseOrder + 6,
      inTable: false,
    });
  });

  // 3. 條件設定專用欄位 (靜態部分)
  const staticConditionSettingFields = [
    {
      id: "fan_setting_chamber1_supply",
      dataKey: "fan_setting_chamber1_supply",
      label: "FAN_１室給氣 (Hz/RPM)",
      csvHeader: "FAN_１室給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 500,
      inTable: true,
    },
    {
      id: "fan_setting_chamber1_exhaust",
      dataKey: "fan_setting_chamber1_exhaust",
      label: "FAN_１室排氣 (Hz/RPM)",
      csvHeader: "FAN_１室排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 501,
      inTable: true,
    },
    {
      id: "fan_setting_chamber2_supply",
      dataKey: "fan_setting_chamber2_supply",
      label: "FAN_２室給氣 (Hz/RPM)",
      csvHeader: "FAN_２室給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 502,
      inTable: true,
    },
    {
      id: "fan_setting_chamber2_exhaust",
      dataKey: "fan_setting_chamber2_exhaust",
      label: "FAN_２室排氣 (Hz/RPM)",
      csvHeader: "FAN_２室排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 503,
      inTable: true,
    },
    {
      id: "fan_setting_upper_ac_exhaust",
      dataKey: "fan_setting_upper_ac_exhaust",
      label: "FAN_上部AC排氣 (Hz/RPM)",
      csvHeader: "FAN_上部AC排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 504,
      inTable: true,
    },
    {
      id: "fan_setting_upper_ac_supply",
      dataKey: "fan_setting_upper_ac_supply",
      label: "FAN_上部AC給氣 (Hz/RPM)",
      csvHeader: "FAN_上部AC給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 505,
      inTable: true,
    },
    {
      id: "fan_setting_lower_ac_exhaust",
      dataKey: "fan_setting_lower_ac_exhaust",
      label: "FAN_下部AC排氣 (Hz/RPM)",
      csvHeader: "FAN_下部AC排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 506,
      inTable: true,
    },
    {
      id: "fan_setting_lower_ac_supply",
      dataKey: "fan_setting_lower_ac_supply",
      label: "FAN_下部AC給氣 (Hz/RPM)",
      csvHeader: "FAN_下部AC給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 507,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_supply",
      dataKey: "set_temp_chamber1_supply",
      label: "設定_１室給氣 (℃)",
      csvHeader: "設定_１室給氣 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_upper_heat",
      dataKey: "set_temp_chamber1_upper_heat",
      label: "設定_１室上部熱煤 (℃)",
      csvHeader: "設定_１室上部熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.1,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_lower_heat",
      dataKey: "set_temp_chamber1_lower_heat",
      label: "設定_１室下部熱煤 (℃)",
      csvHeader: "設定_１室下部熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.2,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_supply",
      dataKey: "set_temp_chamber2_supply",
      label: "設定_２室給氣 (℃)",
      csvHeader: "設定_２室給氣 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.3,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_right_heat",
      dataKey: "set_temp_chamber2_right_heat",
      label: "設定_２室右熱煤 (℃)",
      csvHeader: "設定_２室右熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.4,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_middle_heat",
      dataKey: "set_temp_chamber2_middle_heat",
      label: "設定_２室中熱煤 (℃)",
      csvHeader: "設定_２室中熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.5,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_left_heat",
      dataKey: "set_temp_chamber2_left_heat",
      label: "設定_２室左熱煤 (℃)",
      csvHeader: "設定_２室左熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.6,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_left",
      dataKey: "dryer_chamber1_lower_left",
      label: "乾燥機內實溫_１室下 左 (°C)",
      csvHeader: "乾燥機內實溫_１室下 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 520,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_middle",
      dataKey: "dryer_chamber1_lower_middle",
      label: "乾燥機內實溫_１室下 中 (°C)",
      csvHeader: "乾燥機內實溫_１室下 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 521,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_right",
      dataKey: "dryer_chamber1_lower_right",
      label: "乾燥機內實溫_１室下 右 (°C)",
      csvHeader: "乾燥機內實溫_１室下 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 522,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_left",
      dataKey: "dryer_chamber1_upper_left",
      label: "乾燥機內實溫_１室上 左 (°C)",
      csvHeader: "乾燥機內實溫_１室上 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 523,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_middle",
      dataKey: "dryer_chamber1_upper_middle",
      label: "乾燥機內實溫_１室上 中 (°C)",
      csvHeader: "乾燥機內實溫_１室上 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 524,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_right",
      dataKey: "dryer_chamber1_upper_right",
      label: "乾燥機內實溫_１室上 右 (°C)",
      csvHeader: "乾燥機內實溫_１室上 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 525,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_left",
      dataKey: "dryer_chamber2_upper_left",
      label: "乾燥機內實溫_２室上 左 (°C)",
      csvHeader: "乾燥機內實溫_２室上 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 526,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_middle",
      dataKey: "dryer_chamber2_upper_middle",
      label: "乾燥機內實溫_２室上 中 (°C)",
      csvHeader: "乾燥機內實溫_２室上 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 527,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_right",
      dataKey: "dryer_chamber2_upper_right",
      label: "乾燥機內實溫_２室上 右 (°C)",
      csvHeader: "乾燥機內實溫_２室上 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 528,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_left",
      dataKey: "dryer_chamber2_lower_left",
      label: "乾燥機內實溫_２室下 左 (°C)",
      csvHeader: "乾燥機內實溫_２室下 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 529,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_middle",
      dataKey: "dryer_chamber2_lower_middle",
      label: "乾燥機內實溫_２室下 中 (°C)",
      csvHeader: "乾燥機內實溫_２室下 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 530,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_right",
      dataKey: "dryer_chamber2_lower_right",
      label: "乾燥機內實溫_２室下 右 (°C)",
      csvHeader: "乾燥機內實溫_２室下 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 531,
      inTable: true,
    },
    {
      id: "dryer_top_roll_chamber",
      dataKey: "dryer_top_roll_chamber",
      label: "乾燥機內實溫_Top Roll室 (°C)",
      csvHeader: "乾燥機內實溫_Top Roll室 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 532,
      inTable: true,
    },
    {
      id: "dryer_impregnation_chamber",
      dataKey: "dryer_impregnation_chamber",
      label: "乾燥機內實溫_含浸室 (°C)",
      csvHeader: "乾燥機內實溫_含浸室 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 533,
      inTable: true,
    },
  ];

  // 4. 條件設定專用欄位 (Damper, 動態)
  const damperFields = (allDamperOpeningFields[currentDryerModel] || []).map(
    (field) => ({ ...field, recordTypes: ["conditionSetting"] })
  );

  // 5. 條件設定專用欄位 (HMI, 動態)
  const hmiGeneratedFields = [];
  const modelHmiConfig = hmiFieldsByModel[currentDryerModel] || {};
  for (const sectionKey in modelHmiConfig) {
    const fieldsInSection = modelHmiConfig[sectionKey] || [];
    fieldsInSection.forEach((field) => {
      hmiGeneratedFields.push({
        id: field.id,
        dataKey: `hmiData.${sectionKey}.${field.id}`,
        label: field.label,
        csvHeader: `HMI_${field.label
          .replace(/<small>.*<\/small>/, "")
          .replace(/\d+\.\s*/, "")}`,
        recordTypes: ["conditionSetting"],
        group: sectionKey,
        elemType: "number",
        order: 700 + (parseInt(field.label) || 0),
        inTable: true,
        validation: field.validation,
        isHmiField: true,
        position: field.position,
      });
    });
  }

  // 6. 組合所有欄位
  const allFields = [
    ...baseFields,
    ...recorder1Fields,
    ...recorder2Fields,
    ...airAndExternalFields,
    ...airVolumeGeneratedFields,
    ...techTempGeneratedFields,
    ...staticConditionSettingFields,
    ...damperFields,
    ...hmiGeneratedFields,
  ];

  allFields.sort((a, b) => (a.order || Infinity) - (b.order || Infinity));
  return allFields;
};

const getAirAndExternalFieldsByModel = (model) => {
  const commonFields = [
    {
      id: "airExternal_chamber1_supply_hz_rpm",
      dataKey: "airExternal_chamber1_supply_hz_rpm",
      label: "一室給氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_一室給氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 32,
      inTable: true,
    },
    {
      id: "airExternal_chamber1_exhaust_hz_rpm",
      dataKey: "airExternal_chamber1_exhaust_hz_rpm",
      label: "一室排氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_一室排氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 33,
      inTable: true,
    },
    {
      id: "airExternal_chamber2_supply_hz_rpm",
      dataKey: "airExternal_chamber2_supply_hz_rpm",
      label: "二室給氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_二室給氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 34,
      inTable: true,
    },
    {
      id: "airExternal_chamber2_exhaust_hz_rpm",
      dataKey: "airExternal_chamber2_exhaust_hz_rpm",
      label: "二室排氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_二室排氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 35,
      inTable: true,
    },
    {
      id: "airExternal_top_roll_chamber_celsius",
      dataKey: "airExternal_top_roll_chamber_celsius",
      label: "Top ROLL室 (℃)",
      csvHeader: "風量設定&機外顯示_Top ROLL室 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 36,
      inTable: true,
    },
    {
      id: "airExternal_top_exhaust_hz",
      dataKey: "airExternal_top_exhaust_hz",
      label: "Top排 (Hz)",
      csvHeader: "風量設定&機外顯示_Top排 (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 37,
      inTable: true,
    },
    {
      id: "airExternal_ac_hz",
      dataKey: "airExternal_ac_hz",
      label: "AC (Hz)",
      csvHeader: "風量設定&機外顯示_AC (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38,
      inTable: true,
    },
    {
      id: "airExternal_impregnation_chamber_celsius",
      dataKey: "airExternal_impregnation_chamber_celsius",
      label: "含浸室 (℃)",
      csvHeader: "風量設定&機外顯示_含浸室 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 39,
      inTable: true,
    },
  ];
  const modelSpecificFields = [];
  if (model === "vt6") {
    modelSpecificFields.push({
      id: "airExternal_upper_ac_exhaust_hz",
      dataKey: "airExternal_upper_ac_exhaust_hz",
      label: "上AC排 (Hz)",
      csvHeader: "風量設定&機外顯示_上AC排 (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38.1,
      inTable: true,
    });
  } else if (model === "vt7") {
    modelSpecificFields.push({
      id: "airExternal_built_in_ac_hz",
      dataKey: "airExternal_built_in_ac_hz",
      label: "內建AC (Hz)",
      csvHeader: "風量設定&機外顯示_內建AC (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38.2,
      inTable: true,
    });
  }
  const combinedFields = [...commonFields, ...modelSpecificFields];
  combinedFields.sort((a, b) => a.order - b.order);
  return combinedFields;
};

// 最後，將所有需要的設定和函式一起匯出
export {
  LOCAL_STORAGE_KEY,
  techTempPoints,
  generateFieldConfigurations,
  getAirVolumeMeasurementsByModel,
  allDryerAirVolumeMeasurements,
  hmiLayouts,
  hmiFieldsByModel,
  allDamperOpeningFields,
  damperLayoutsByModel,
};
